#!/usr/bin/python3
"""This module contains a Fabric script (based on the file
    1-pack_web_static.py) that distributes an archive to
    your web servers, using the function do_deploy.
    """

from fabric.api import *
import os

env.user = "ubuntu"
env.hosts = ['100.25.205.228', '100.25.211.79']


def do_deploy(archive_path):
    """uncompress an archive file into a remote server directory
    """
    if not os.path.exists(archive_path):
        return False

    # deploy the archive file to the remote server
    put(archive_path, "/tmp/")

    # remove the achive name only from the path given
    archive_name = os.path.basename(archive_path)

    # Get the archive file name without extension
    arch_filename = os.path.splitext(archive_name)[0]

    # the path to the remote archive file
    arch_path = f'/tmp/{archive_name}'

    run(f'mkdir -p /data/web_static/releases/{arch_filename}')

    # uncompress the archive file
    cmd = 'tar -xzvf {} -C /data/web_static/releases/{} --strip-components=1'
    run(cmd.format(arch_path, arch_filename)

    #delete the archive from the webserver
    run('rm arch_path')

    # delete the initial symbolic link on the web server
    run('rm /data/web_static/current')

    # create new symbolic link
    run(f'ln -s /data/web_static/releases/{arch_filename} /data/web_static/current')
    return True
